[package]
authors = ["theduke <chris@theduke.at>"]
name = "crates_io_api"
description = "API client for crates.io"
license = "MIT/Apache-2.0"
repository = "https://github.com/theduke/crates_io_api"
documentation = "https://docs.rs/crates_io_api"
readme = "README.md"
keywords = [ "crates", "api" ]
categories = [ "web-programming", "web-programming::http-client" ]
edition = "2018"

version = "0.5.1"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
reqwest = {version = "0.10.4", features = ["blocking","json"] }
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.48"
url = "2.1.1"
log = "0.4.8"
failure = "0.1.7"
futures = "0.3.4"
tokio = { version= "0.2.13", features = ["macros"] }
